on: [push, pull_request]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-minimal:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: [ '2.3', '2.4', '2.5' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          ruby ltx2any.rb
  test-pdflatex:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            latex-bin scheme-basic
      - name: ltex2any
        run: |
          cd test
          ruby ../ltx2any.rb test.tex
      - uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: |
            test/test.pdf
            test/test.log.md
