on: [push, pull_request]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-minimal:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
        ruby: [ '2.3', '2.4', '2.5' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          ruby ltx2any.rb
  test-pdflatex:
    runs-on: ubuntu-20.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Prepare Dockerfile
        run: cp test/Dockerfile .
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: localhost:5000/name/app:latest
          file: test/Dockerfile
      - name: ltx2any
        run: docker run -v $(pwd)/test:/work/src localhost:5000/name/app:latest work "/ltx2any/ltx2any ../src/test.tex"
      - uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: |
            test/test.pdf
            test/test.log.md
